### PR TITLE
[3.2 compatibility] Make an empty hash shift return nil

### PR DESCRIPTION
**Pull request by itarato**
Ruby 3.2 empty Hash, when `#shift` is applied returns a `nil`. This PR makes this update for truffleruby.

> Hash#shift now always returns nil if the hash is empty, instead of returning the default value or calling the default proc. [[Bug #16908](https://bugs.ruby-lang.org/issues/16908)]

### CODE REVIEW

**Comment by andrykonchin** [comment]
Thank you. Changes look good for me.

Regarding the failed specs - will look at the issue soon.

**Comment by andrykonchin** [comment]
I am not able to push my changes into this remote branch because of the following error.

> ERROR: Permission to Shopify/truffleruby.git denied to andrykonchin.

So this PR will be marked as merged when an internal PR is merged.

**Review by andrykonchin — APPROVED** [review]

**Comment by nirvdrum** [comment]
@andrykonchin I don't think we need to tag any failing specs. Those specs will fail in _master_ because _master_ targets Ruby 3.1. We should have a 3.2-upgrade branch that either changes the version number to 3.2.2 or runs all specs with `:next`. At least, that's my understanding of the process. We don't support more than one Ruby version at a time, so this PR can't be merged into _master_ yet.

**Comment by andrykonchin** [comment]
I've canceled the merging workflow for this PR. Will discuss it with Benoit next week.

AFAIK our current approach is to merge only not harmful changes introduced in the next (not supported yet) Ruby version. Both new features and bug fixes I would consider as not harmful TBH.

**Comment by eregon** [comment]
I discussed it with Andrii. CRuby chose to not backport this, so it's in 3.2 but not in 3.1.
The potential of incompatibility seems pretty low (who would rely on this? Any gem testing against 3.1 & 3.2 has to handle this change, and it's easy to feature-detect this change), so I think it's OK to merge this to master.
In case of trouble we can always revert it and reapply it later.

> We should have a 3.2-upgrade branch that either changes the version number to 3.2.2 or runs all specs with `:next`.

@nirvdrum We never had version-upgrade branches, because it's unfeasible in terms of conflicts (especially for the import files from MRI part). Specs listed in `:next` are already run in GH and internal CI.

**Pull request merged**
