### PR TITLE
Add a GitHub Action for building and linting

### PR DESCRIPTION
**Pull request by chrisseaton**
It doesn't currently run:

- the Eclipse formatter, as I haven't added something to download that yet
- the Python formatter, as I haven't installed `pylint` yet

There are some things that could be improved:

- fetch less of the mx and Graal repository histories
- cache mx, JVMCI, and Graal, and perhaps other things we download

Since we can build in GitHub Actions, why aren't we aiming to just run all our tests and specs here?

Note that I believe you can't create a PR to create a GitHub Actions workflow! I think you have to do that in the web UI. But the files you need to add in the UI are there, just called `.github_x` rather than `.github`.

After merging this, you would have to run `jt lint` with `--testpack` in your CI.

https://github.com/Shopify/truffleruby/issues/1

### CODE REVIEW

**Comment by chrisseaton** [comment]
This came up with `chris@chrisseaton.com` because I did it in the UI. Do you need me to re-attribute the commit?

**Comment by eregon** [comment]
@chrisseaton I added that email to the known list, the bot should react soon.

**Comment by chrisseaton** [comment]
Can we merge this?

**Comment by eregon** [comment]
@chrisseaton Could you push a version without the final commit? Can be another PR if easier.
Otherwise the PR won't be marked as merged.

**Comment by chrisseaton** [comment]
Done.

**Comment by eregon** [comment]
Currently GitHub Actions is not available for the TruffleRuby repository. I'll try to figure out if that can change. So until then I migrated the lint check to TravisCI in #1829, which is based on top of this PR.

**Pull request merged**
