### PR TITLE
Redefine Gem::RequestSet::GemDependencyAPI instead of modifying it

### LINKED ISSUE #1558: Incompatibility with Rubygems starting from 3.0.0.beta2
```sh

$ ruby -v
truffleruby 1.0.0-rc11, like ruby 2.4.4, GraalVM CE Native [x86_64-darwin]

$ gem -v
2.6.14.1

$ bundle -v
Bundler version 2.0.1

$ gem update --system
Updating rubygems-update
Fetching: rubygems-update-3.0.2.gem (100%)
Successfully installed rubygems-update-3.0.2
Installing RubyGems 3.0.2
Bundler 1.17.3 installed
RubyGems 3.0.2 installed
Regenerating binstubs
ERROR:  While executing gem ... (RuntimeError)
    can't modify frozen Hash

$ gem -v
3.0.2

 $ bundle -v
/Users/toad/.rbenv/versions/truffleruby-1.0.0-rc11/lib/patches/rubygems/request_set/gem_dependency_api.rb:10:in `[]=': can't modify frozen Hash (RuntimeError)
	from /Users/toad/.rbenv/versions/truffleruby-1.0.0-rc11/lib/patches/rubygems/request_set/gem_dependency_api.rb:10:in `GemDependencyAPI'
	from /Users/toad/.rbenv/versions/truffleruby-1.0.0-rc11/lib/patches/rubygems/request_set/gem_dependency_api.rb:3:in `<top (required)>'
	from /Users/toad/.rbenv/versions/truffleruby-1.0.0-rc11/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `gem_original_require'
	from /Users/toad/.rbenv/versions/truffleruby-1.0.0-rc11/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/toad/.rbenv/versions/truffleruby-1.0.0-rc11/lib/ruby/site_ruby/2.4.0/rubygems/request_set.rb:477:in `<top (required)>'
	from /Users/toad/.rbenv/versions/truffleruby-1.0.0-rc11/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `gem_original_require'
	from /Users/toad/.rbenv/versions/truffleruby-1.0.0-rc11/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/toad/.rbenv/versions/truffleruby-1.0.0-rc11/lib/ruby/site_ruby/2.4.0/rubygems.rb:238:in `finish_resolve'
	from /Users/toad/.rbenv/versions/truffleruby-1.0.0-rc11/lib/ruby/site_ruby/2.4.0/rubygems.rb:305:in `block in activate_bin_path'
	from /Users/toad/.rbenv/versions/truffleruby-1.0.0-rc11/lib/ruby/site_ruby/2.4.0/rubygems.rb:303:in `synchronize'
	from /Users/toad/.rbenv/versions/truffleruby-1.0.0-rc11/lib/ruby/site_ruby/2.4.0/rubygems.rb:303:in `activate_bin_path'
	from /Users/toad/.rbenv/versions/truffleruby-1.0.0-rc11/bin/bundle:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by sponomarev**
Closes #1558

### CODE REVIEW

**Comment by chrisseaton** [comment]
Thanks very much for this contribution!

We don't really support using a new RubyGems with TruffleRuby at the moment, and we're probably going to add code to enforce that and document it properly.

Your patch is very helpful as we'd need to do this work anyway when we update RubyGems with the new version of Ruby, and it's also the code that we need to get on and upstream to RubyGems.

Are you happy to sign the OCA? I can't merge this code without it I'm afraid.

**Comment by sponomarev** [comment]
@chrisseaton I'll sign the OCA once I reach any printer 😄 . Hopefully, tomorrow. 

> it's also the code that we need to get on and upstream to RubyGems

I can take care of it if you think that the time has come.

**Comment by chrisseaton** [comment]
We're already upstreaming what we currently have - https://github.com/rubygems/rubygems/pull/2612. We'll then get this PR in, and then we can upstream again.

**Comment by eregon** [comment]
Trying to clarify a bit: it's useful to merge this PR, as we won't update to the latest RubyGems release containing rubygems/rubygems#2612 right away, but probably use the same version as MRI uses for the corresponding Ruby version we target.

**Comment by sponomarev** [comment]
I'm through with the OCA

**Comment by chrisseaton** [comment]
Great! I just need it to appear on that website which should happen soon.

**Comment by sponomarev** [comment]
No idea why my OCA has not been processed yet 🤷‍♂️

**Comment by chrisseaton** [comment]
I can chase it up for you.

**Comment by chrisseaton** [comment]
You should have received some instructions on how to fix something.

**Comment by sponomarev** [comment]
Thanks, @chrisseaton! That's strange, but I've sent a new copy.

**Comment by sponomarev** [comment]
Hooray! I've just received the confirmation!

**Comment by chrisseaton** [comment]
Yes I see your name on the list now. I will rebase and run CI on this code and we should just be able to squeeze it into RC 13.

**Comment by sponomarev** [comment]
@chrisseaton Please, let me know if I should rebase it.

**Comment by eregon** [comment]
@sponomarev No need, our CI takes care to test on a merge commit with `master` :)

**Comment by chrisseaton** [comment]
Merged.

**Pull request closed without merging**
