### PR TITLE
rb_gc_force_recycle is now no-op, Ruby 3.1 support

### PR DESCRIPTION
**Pull request by moste00**
Removed the body of rb_gc_force_recycle, a C API function that https://github.com/oracle/truffleruby/issues/2733 says that is deprecated and should be made a no-op. Full text search confirms it's not used anywhere.

### CODE REVIEW

**Comment by andrykonchin** [comment]
Linter fails with error:

```
Check the diff of this PR, and:
* if ABI has changed, then increment lib/cext/ABI_version.txt
* if ABI has not changed, then increment lib/cext/ABI_check.txt

Changing headers or compilation flags, as well as removing/adding a non-static function
(because e.g. mkmf have_func can depend on that) should all be considered ABI changes.
```

So one more change required - looks like ABI wasn't changes so could you please increment `lib/cext/ABI_check.txt` (it should probably be done in the same commit with changes in a header so satisfy the linter check)

**Comment by eregon** [comment]
> Full text search

Do you mean GitHub search? I wouldn't trust that, rather `git grep` or so is reliable.

**Comment by eregon** [comment]
Upstream is https://github.com/ruby/ruby/blob/ruby_3_1/gc.c#L8675-L8679
Could you copy-paste that function declaration so we have exactly the same?

It's also deprecated here https://github.com/ruby/ruby/blob/ruby_3_1/include/ruby/internal/intern/gc.h#L213-L214
but we already have that: https://github.com/oracle/truffleruby/blob/82f5ec3122be617d8a82ed43856fe51f79807e28/lib/cext/include/ruby/internal/intern/gc.h#L213 so that part is already done.

**Comment by moste00** [comment]
> Do you mean GitHub search?

Oh I meant Intellij IDEA, I did "find in files" and it found nothing except the .h and .c where it's defined. I did git grep just now and it agrees.



> Could you copy-paste that function declaration so we have exactly the same?

Hmmm, is there an automated check for that which we would like to pass ? It's the same exact function with a different formatting, I will do it anyway but I don't understand why we should string-match the exact file in CRuby :'D.

**Comment by moste00** [comment]
> So one more change is required.

Done now.

**Comment by eregon** [comment]
> Hmmm, is there an automated check for that which we would like to pass ? It's the same exact function with a different formatting, I will do it anyway but I don't understand why we should string-match the exact file in CRuby :'D.

Yeah we don't have to match exactly, e.g. we can respect the style of this file with 2-spaces indent and return type and `{` on the same line, etc. But it's good to look very close to the original so it's easy to compare with a glance.
Notably here we wouldn't want to keep the outdated comment.

**Review by eregon — APPROVED** [review]

**Pull request merged**
