### PR TITLE
Use llvm-linker to combine library bitcode files.

### PR DESCRIPTION
**Pull request by aardvark179**
This resolves some sulong function resolution bugs in C extensions.

### CODE REVIEW

**Comment by aardvark179** [comment]
The 'oj' extension cannot be loaded unless the files have been linked, it fails while resolving function array literals.

Testing this feels like it might be more involved with Sulong's internals than we'd really want.

**Comment by eregon** [comment]
> The 'oj' extension cannot be loaded unless the files have been linked, it fails while resolving function array literals.

We could test just installing the `oj` gem if that works (like puma/sqlite3/unf_ext in the gem test pack).

**Comment by chrisseaton** [comment]
I think it's ok to leave testing gems to the module tester. Just make sure 'oj' is in it if it now works.

**Comment by pitr-ch** [comment]
I think testing few key gems in our CI is good for catching regressions.

**Pull request merged**
