### PR TITLE
Fixes https://github.com/oracle/truffleruby/issues/1457

### PR DESCRIPTION
**Pull request by ioquatix**

### CODE REVIEW

**Comment by ioquatix** [comment]
Are there any specs for this?

**Comment by ioquatix** [comment]
Okay, I signed.

**Comment by ioquatix** [comment]
Here is a monkey patch: https://github.com/socketry/async-io/commit/3380a7dfe4e973b7abf383bd3f7508ccc14f906f

**Comment by ioquatix** [comment]
I also think this implementation has poor performance because the entire point is to avoid throwing exceptions as part of normal flow control. We should be checking errno directly and checking what to do.

**Comment by eregon** [comment]
> Are there any specs for this?

Yes, there is https://github.com/oracle/truffleruby/blob/2788048c2f037f42c095ad69486c96f49556aa28/spec/ruby/core/io/write_nonblock_spec.rb#L69-L74
which can be enabled with
```
$ jt untag spec/ruby/core/io/write_nonblock_spec.rb
```

**Comment by ioquatix** [comment]
From what I could see, `IO.pipe` might use a slightly different code path to `socket`.

**Comment by eregon** [comment]
> From what I could see, `IO.pipe` might use a slightly different code path to `socket`.

They are both `IO` instance and do not redefine `write_nonblock`, so they should behave the same in TruffleRuby.
It would be nice to have an extra spec for `Socket#write_nonblock` though, I agree.

**Comment by ioquatix** [comment]
Here is the other implementation.

https://github.com/oracle/truffleruby/blob/63691ad7cd1cb9d57358f9b527aed0fbefb9d641/src/main/ruby/core/io.rb#L2775-L2777

**Comment by eregon** [comment]
Right, there is also `IO::BidirectionalPipe`, I missed that.
That one seems used only in `IO.popen` and nowhere else.

**Comment by eregon** [comment]
@ioquatix I merged your PR in 78231bc55170f37dd5394f87b997cfcabbcfd7b7 and added an entry to the changelog, thank you!

> Here is a monkey patch: [socketry/async-io@3380a7d](https://github.com/socketry/async-io/commit/3380a7dfe4e973b7abf383bd3f7508ccc14f906f)

Would you be interested to make a PR with those changes? That'd be great :)
Since they are closely related changes, it's fine to have them all in the same PR.

**Pull request closed without merging**
