### PR TITLE
Process::Status#==: compare raw process status

### PR DESCRIPTION
**Pull request by XrXr**

### CODE REVIEW

**Comment by XrXr** [comment]
Ah, already included in #1800

**Comment by eregon** [comment]
The specs are not though and would be useful, could you rebase this once #1800 is merged?

**Comment by eregon** [comment]
@XrXr #1800 was merged, could you rebase this PR on top?

**Comment by XrXr** [comment]
Rebased. Let me know if you need a changelog entry.

**Comment by eregon** [comment]
Thanks, merged.

**Pull request merged**
