### PR TITLE
Remove obsolete patches of rake-compiler

### PR DESCRIPTION
**Pull request by larskanis**
They were introduced in https://github.com/oracle/truffleruby/pull/536 but are obsolete since commit 3172a3ef18dc8b721aba251546b1ccbd57721108 .

This also fixes a "version for nil" error when rake-compiler isn't installed as gem, as happening when rake-compiler's "rake spec" is executed.

### CODE REVIEW

**Comment by eregon** [comment]
@larskanis Thank you for the PR. Indeed, now that we use the standard DLEXT and OBJEXT on both Linux and macOS the patch should no longer be needed.

I thought to actually upstream those patches (because `RbConfig::CONFIG["DLEXT"]` is nicer than hardcoding it) but there is no easy way to get the extensions for all platforms and not just the current platform. So this sounds good.

**Comment by larskanis** [comment]
@eregon Indeed `RbConfig::CONFIG["DLEXT"]` would be nicer and in fact it would be possible to read this information out of the `rbconfig.rb` files of all installed cross rubies within rake-compiler. However I don't think this is worth the effort having practically only two possible file extensions.

For what it's worth I signed, scanned and mailed the ugly Oracle Contributor Agreement.

**Comment by eregon** [comment]
Thank you for submitting the OCA. It might take a bit longer to process given that many people are on holidays.

**Comment by eregon** [comment]
@larskanis Thank you for the PR, it's merged now.
I am sorry it took a while for the OCA to be processed.

**Comment by larskanis** [comment]
Alright!

**Pull request merged**
