### PR TITLE
[3.2 compatibility] Fix array slice with arithmetic sequence for Ruby v3.2

### PR DESCRIPTION
**Pull request by itarato**
Ruby 3.2 is applying slice with an `Enumerator::ArithmeticSequence` argument slightly differently: for negative steps and exclusive-ending range the start/end is adjusted in this PR.

Related Ruby core issue: https://bugs.ruby-lang.org/issues/18247

Specs: https://github.com/oracle/truffleruby/commit/7d5bad88ae9499ce8de99c1ee263b23ef8ba432b#diff-5359533868e5029f9a20bc73cd77a856a8557d94d2726006cd218b14e3c87c4eR787-R881

### CODE REVIEW

**Comment by andrykonchin** [comment]
Any specs covered this new behaviour would be appreciated. Also could you please point at description of this change (CRuby bug tracker issue, PR or commit in the CRuby reopsitory)?

**Comment by itarato** [comment]
> Any specs covered this new behaviour would be appreciated.

This PR is fixing broken tests for v3.2: https://github.com/oracle/truffleruby/commit/7d5bad88ae9499ce8de99c1ee263b23ef8ba432b#diff-5359533868e5029f9a20bc73cd77a856a8557d94d2726006cd218b14e3c87c4eR787-R881 These already exist.

> Also could you please point at description of this change (CRuby bug tracker issue, PR or commit in the CRuby reopsitory) - I haven't found any mentioning in the release notes/news? Could it be this one https://bugs.ruby-lang.org/issues/18247?

Correct. That's the thread that led to the extra specs.

Anything else should be added?

@andrykonchin

**Review by andrykonchin — APPROVED** [review]
Thank you!

**Comment by andrykonchin** [comment]
> Anything else should be added?

There are some additional steps that are supposed to be done in such PRs:
- to add a changelog record
- to tag failed specs that are supposed to fail because of new changes (e.g. in #2980)
- to add files with specs for a new feature to the `:next` list (in `spec/truffleruby.mspec`, see [guide](https://github.com/oracle/truffleruby/blob/master/doc/contributor/workflow.md#running-specs-for-ruby-32-features))

I've done them already for the existing PRs (this one and #2980) so there is nothing to do. The PRs will be merged when pass our internal CI.

**Pull request merged**
