### PR TITLE
Keep method name symbols for alive methods alive

### PR DESCRIPTION
**Pull request by chrisseaton**
Opening this to get your opinion on the problem this solves. *Please don't complain about the location of the specs we'll move them when we're happy with the solution.*

https://github.com/Shopify/truffleruby/issues/1

### CODE REVIEW

**Comment by eregon** [comment]
Is there something depending on `Symbol.all_symbols` returning method names (and therefore methods leaking their name symbol forever)?

**Comment by eregon** [comment]
If we add this, we should take advantage of it in `LiteralMethodDefinitionNode` which currently does `getSymbol(name)`.

**Comment by chrisseaton** [comment]
Did you already read the commit message?

**Comment by chrisseaton** [comment]
> If we add this, we should take advantage of it in LiteralMethodDefinitionNode which currently does getSymbol(name).

Fixed.

**Comment by eregon** [comment]
I missed the commit message:

> Keep method name symbols for alive methods alive
> 
> Liquids has a security test which asserts that there is no growth in
> entry count for the symbol table when parsing and rendering. It may
> happen that some method name symbols used in the call graph of said
> security test is GC'ed prior to the test running, but are recreated
> during the execution of the test. This causes test flakiness as
> different test orders affect what method name symbols are alive when the
> security test runs.

I guess it's these:
https://github.com/Shopify/liquid/blob/b7f0f158ab3f5c8c51baea00418a275380a1ff9c/test/integration/security_test.rb#L46-L67

If anything creates a Symbol during that test it's still a Liquid bug though, isn't it?
Is it that liquid defines well-known methods during that test (which create Symbols dynamically in TruffleRuby)? That would sound surprising to me.

> This fix keeps a reference to the method name symbol inside
> InternalMethod. This keeps the symbol alive and present in the symbol
> table.
> 
> Some symbols are GC roots in MRI and I don't think there is something
> equivalent in Truffle. Let's see if this commit alone is enough to
> address Liquid's issue.

Is it enough to pass the test reliably?

**Comment by eregon** [comment]
cc @XrXr 

I got it to fail by adding GC.start calls inside the test:
```
  1) Failure:
SecurityTest#test_does_not_add_filters_to_symbol_table [/home/eregon/code/liquid/test/integration/security_test.rb:55]:
Expected: []
  Actual: [:match_onwards]

  2) Failure:
SecurityTest#test_does_not_add_drop_methods_to_symbol_table [/home/eregon/code/liquid/test/integration/security_test.rb:74]:
--- expected
+++ actual
@@ -1 +1 @@
-[]
+[:find_variable, :try_variable_find_in_environments, :lookup_and_evaluate]
```

**Comment by eregon** [comment]
I'm not sure what creates these symbols *during the test*, but it sounds worth finding out.
For the second failure, all 3 names are from method from context.rb which should have been defined a long time before.
For the first failure, `match_onwards` is a `@CoreMethod` of TruffleRuby.
That's even more weird.

Maybe some call sites create a Symbol for the method they are calling?
That sounds plausible, `CachedDispatchNode#cachedNameAsSymbol` does do that.
We should do it lazily, I'll try that.

**Comment by eregon** [comment]
https://github.com/oracle/truffleruby/compare/master...eregon:bd/cache-symbol-in-call-node-only-when-needed does seem to fix the test, by actually leaking less Symbols :)

I'll merge that approach, because it's quite a bit better for memory footprint.

**Comment by eregon** [comment]
I merged my fix in 97ec341bd2ef2d6492bc9b4937e39253aca4a0f3.
That let the test pass when I ran it locally.

**Pull request closed without merging**
