### PR TITLE
Provide a fallback implementation of IO#nread

### PR DESCRIPTION
**Pull request by chrisseaton**

### CODE REVIEW

**Comment by eregon** [comment]
What should IO#nread do? Is there a test/spec to ensure the current fallback works well enough? Could it cause infinite loops due to always returning 0?

**Comment by chrisseaton** [comment]
It seems to be a very untested API. No specs and only two MRI tests! But the docs say

> Returns zero if no information available.

So returning zero seems to be an ok fallback. And the bottom line is this fixes Webrick for the 1.0 release. Please approve.

**Comment by chrisseaton** [comment]
To answer literally what does it do, it returns the number of bytes which can be read without blocking.

**Comment by eregon** [comment]
Thanks for the information, it sounds fine. I was away so I couldn't approve.

**Pull request merged**
