### PR TITLE
Add Ripper constructor and noop methods

### LINKED ISSUE #1692: Ripper.new(code) - `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
Maybe it's related to https://github.com/oracle/truffleruby/issues/1585 but the following code throws an exception in TruffleRuby 19:

```rb
require 'ripper'

p Ripper.new("print 'hello world'")
```

```console
$ rvm use truffleruby-19.0.0
Using /Users/guillaumegrossetie/.rvm/gems/truffleruby-19.0.0
$ ruby test.rb
test.rb:3:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from test.rb:3:in `new'
	from test.rb:3:in `<main>'
```

```console
$ rvm use ruby-2.6@asciidoctor
Using /Users/guillaumegrossetie/.rvm/gems/ruby-2.6.3
$ ruby test.rb
#<Ripper:0x00007fdc1b12fc38>
```

Ripper is used in [Temple](https://github.com/judofyr/temple) which is used in [Haml](https://github.com/haml/haml) which is used in [Asciidoctor](https://github.com/asciidoctor/asciidoctor) 😉 

https://github.com/judofyr/temple/blob/7987ab67af00a598eb3d83192415371498a0f125/lib/temple/static_analyzer.rb#L58

### PR DESCRIPTION
**Pull request by Mogztter**
resolves #1692

### CODE REVIEW

**Comment by Mogztter** [comment]
I've sent the requested document.

**Comment by chrisseaton** [comment]
Thanks. It takes a few days to show up (and Monday is a federal holiday in the United States.)

**Comment by Mogztter** [comment]
No worries, did you receive my email ?

**Comment by chrisseaton** [comment]
I'll chase it up - doesn't come directly to an individual.

**Comment by Mogztter** [comment]
> I'll chase it up - doesn't come directly to an individual.

Ok, let me know if you can't find it, I can send it again to you the right person 😉

**Comment by chrisseaton** [comment]
Thanks the OCA came through. I'm running this through our CI now.

**Comment by eregon** [comment]
@Mogztter Thank you for the PR! It's merged now.

**Comment by Mogztter** [comment]
Thanks, looking forward to the next release :smiley:

**Pull request merged**
