### PR TITLE
Support sourcing the Spin environment file from a Bash script

### PR DESCRIPTION
**Pull request by tomstuart**
At Shopify we want to use TruffleRuby inside other Spin projects, so it’s important that `source /path/to/truffleruby/.spin/bin/env` works from those projects’ Bash scripts as well as directly from the command line.

When the environment file is sourced by another script, `$0` is the name of the main script being executed rather than the environment file itself, so `dirname "$0"` will return the (probably incorrect) directory containing the main script rather than `/path/to/truffleruby/.spin/bin` as expected.

In Bash, [`$BASH_SOURCE`](https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#index-BASH_005fSOURCE) is an array containing the source filenames of all currently-executing shell functions, of which the first is [always the most recent](https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#index-FUNCNAME), so we can use `$BASH_SOURCE[0]` to directly ask for the filename of the environment file instead of assuming that `$0` will contain it.

We also need to be able to source the environment file directly from a Zsh command line, but `$BASH_SOURCE` isn’t supported by Zsh so doesn’t work for the latter purpose. We therefore use shell [parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) syntax to supply a Zsh-compatible equivalent if `$BASH_SOURCE` isn’t set.

The expression `${(%):-%x}` in Zsh does the same job as `$BASH_SOURCE` in Bash: `(%)` is a [parameter expansion flag](https://zsh.sourceforge.io/Doc/Release/Expansion.html#index-parameter-expansion-flags) which enables [prompt sequence expansion](https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html) in what follows, and [`%x`](https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html#Shell-state) is the prompt sequence for “the name of the file containing the source code currently being executed”.

### CODE REVIEW

**Review by nirvdrum — APPROVED** [review]
Looks good to me. Although having the shebang line execute Bash and having ZSH syntax is a bit non-obvious. Maybe add a comment above the `SCRIPT_PATH` line indicating the fallback is for ZSH?

**Comment by chrisseaton** [comment]
Wow all this for `__dir__`!

**Review by eregon — APPROVED** [review]
Fine for me.
It seems so far we haven't needed to source shell files from ZSH (rather we typically execute such files with Bash).

**Comment by tomstuart** [comment]
Great, thanks both!

**Comment by tomstuart** [comment]
> Although having the shebang line execute Bash and having ZSH syntax is a bit non-obvious.

@nirvdrum What do you think about removing the shebang altogether? The only legitimate use of this script is to be `source`d because the whole point of it is to set environment variables, so anybody who’s executing it directly is using it wrong. So maybe we should `chmod a-x` it and remove the shebang so that you can’t even try to do that?

**Comment by nirvdrum** [comment]
> @nirvdrum What do you think about removing the shebang altogether? The only legitimate use of this script is to be `source`d because the whole point of it is to set environment variables, so anybody who’s executing it directly is using it wrong. So maybe we should `chmod a-x` it and remove the shebang so that you can’t even try to do that?

That was the train of thought I was going down, but I wasn't sure if there were applications where the script is intended to be run directly. If the script shouldn't be invoked, then I think the shebang and executable bit might be a bit misleading.

**Comment by eregon** [comment]
Right, at least I think making it non-executable makes sense if it only works when sourced (which is the case, otherwise it doesn't do anything). The shebang might be useful to guess the language in editors, but is probably more confusing than helping if it's not meant to be executed.
@tomstuart Could you do both?

**Comment by tomstuart** [comment]
Okay, done.

**Pull request merged**
