### PR TITLE
Fix `String#dump` formatting of escaped unicode characters

### PR DESCRIPTION
**Pull request by meganniu**
With this PR, `"\u0080".dump` correctly returns `"\u0080"` instead of `"\u{80}"`.

### CODE REVIEW

**Comment by chrisseaton** [comment]
Are you trying to merge to get rid of the conflicts? It's a GitHub bug - there are no conflicts! Feel free to ignore it.

**Comment by meganniu** [comment]
> Hello Megan Niu, thanks for contributing a PR to our project!
> 
> We use the [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html) to make the copyright of contributions clear. We don't have a record of you having signed this yet, based on your email address megan -(dot)- niu -(at)- gmail -(dot)- com. You can sign it at that link.
> 
> If you think you've already signed it, please comment below and we'll check.

Signed and sent! Just waiting for it to be processed :)

**Review by chrisseaton — APPROVED** [review]
Great first contribution to TruffleRuby!

**Comment by eregon** [comment]
Thank you for the PR!

Could you rebase on top of latest master?
We try to avoid merge commits inside PRs (so there is no "merge of merge").

I confirmed your OCA is being processed.

**Review by eregon — APPROVED** [review]

**Pull request merged**
