### PR TITLE
Coerce right hand operand if a BigDecimal is the left hand operator

### LINKED ISSUE #1507: BigDecimal: #coerce method is not called when BigDecimal is left hand operand
See @janko-m's comment with an example to reproduce it https://github.com/oracle/truffleruby/issues/1507#issuecomment-445162208

**Old report**
I've tried TrufflyRuby `1.0.0-rc10` and Sequel's specs. Good news, the most specs pass successfully now. But with one exception: `BigDecimal('1.0') * Sequel[:a][:y]`

This happens only with `BigDecimal` until now. 

To reproduce

```ruby
require 'sequel'
BigDecimal('1.0') * Sequel[:a][:y]
```

Error:

```
NoMethodError: undefined method `to_f' for #<Sequel::SQL::QualifiedIdentifier @column=>:y, @table=>"a">:Sequel::SQL::QualifiedIdentifier
Did you mean?  to_s
	from (irb):2:in `*'
	from (irb):2
	from ~/.rubies/truffleruby-1.0.0-rc10/bin/irb:29:in `<main>'
```

There is no issue e.g. with `float`

```
1.0 * Sequel[:a][:y]
=> #<Sequel::SQL::NumericExpression @args=>[1.0, #<Sequel::SQL::QualifiedIdentifier @column=>:y, @table=>"a">], @op=>:*>
```

### PR DESCRIPTION
**Pull request by Quintasan**
Closes #1507

### CODE REVIEW

**Comment by chrisseaton** [comment]
Looks good. You'll need to do the OCA procedure, please, if you want this merged, as we discussed. Could you also add a change-log entry? The format should be obvious.

Thanks very much for the contribution.

**Comment by Quintasan** [comment]
@chrisseaton I have sent a signed copy of OCA as well

**Comment by chrisseaton** [comment]
I'll start our CI process.

Thanks for signing the OCA - it may take a while to be processed this time of year.

**Comment by chrisseaton** [comment]
You haven't appeared on the OCA list yet - this is probably due to people being away for the holiday break.

**Comment by chrisseaton** [comment]
Still not on the list - I understand @Quintasan has been talking to the OCA people directly about this.

**Comment by chrisseaton** [comment]
I don't know where your OCA has got to - tomorrow is the last day to get this into RC 12.

**Comment by deepj** [comment]
@chrisseaton Any news about this PR? This helps to pass sequel specs.

**Comment by chrisseaton** [comment]
@deepj I can't merge it until the author appears on the OCA list. He's indicated that he's planning to sign it but it hasn't turned up on the official list yet.

**Comment by Quintasan** [comment]
@chrisseaton It appears that I have made a mistake when filling in the OCA. I (hopefully) fixed and resubmitted a signed copy of OCA.

**Comment by chrisseaton** [comment]
I'm told that your OCA is 'in the pipeline.'

**Comment by chrisseaton** [comment]
Merged, thanks.

**Comment by eregon** [comment]
Reopening, as only + and - were fixed, not yet other operators. Also see #1598.

**Pull request closed without merging**
