### PR TITLE
add dockerfiles and github actions to generate and publish docker images

### PR DESCRIPTION
**Pull request by flavorjones**
This PR adds dockerfiles and github actions to generate and publish OCI images to this repository's "packages" at ghcr.io/oracle/truffleruby. There's also a `tool/dockerfiles/README.md` that explains a bit more what's going on.

These images are intended to replace the ones I'm currently maintaining at https://github.com/flavorjones/docker-truffleruby per the conversation I had with @eregon at https://github.com/flavorjones/docker-truffleruby/issues/5#issuecomment-824134973

I've built test images on my fork with these files and actions, if you want to see what the result looks like:

- packages: https://github.com/flavorjones/truffleruby/pkgs/container/truffleruby (available as `ghcr.io/flavorjones/truffleruby:nightly`, for example)
- actions:
  - https://github.com/flavorjones/truffleruby/actions/workflows/docker-nightly.yml
  - https://github.com/flavorjones/truffleruby/actions/workflows/docker-stable.yml

### CODE REVIEW

**Comment by eregon** [comment]
Thank you a lot for this contribution!

Publishing Docker images requires internal approvals, we will check them, it might take some time.

There are also Oracle Linux-based images at https://github.com/graalvm/container/pkgs/container/truffleruby, it is not clear yet where the Debian-based images should be.

**Comment by flavorjones** [comment]
I'm happy to continue to publish "unofficial" images while this wends its way through Oracle approvals.

**Comment by flavorjones** [comment]
Also: I just signed the CLA.

**Comment by flavorjones** [comment]
Just a quick note: This morning I used the action at https://github.com/flavorjones/truffleruby/actions/workflows/docker-stable.yml to manually kick off a new image for 21.2.0.1 and it worked perfectly and took about two minutes. See https://github.com/flavorjones/truffleruby/pkgs/container/truffleruby/versions !

**Comment by eregon** [comment]
@flavorjones I checked with @ezzarghili and his team, and for the next release (Oct 19, 2021) they plan to create official Docker images based on Debian.
However, they want to use their own process & QA for it, to be consistent with Oracle Linux-based images, with what they do in general for releases and importantly to be compliant with Oracle policies regarding Docker images (for instance, images must also be pushed to the [Oracle Container Registry](https://container-registry.oracle.com)).

I really like the automated approach you use here, but for the reasons above we unfortunately can't just merge this PR.

I think it would be best to keep the Docker images at [flavorjones/truffleruby](https://github.com/flavorjones/truffleruby/pkgs/container/truffleruby/versions) for compatibility and people already using them, and I'm happy to keep linking to them from the README.
Also I think the nightly images from there are quite useful, and there is currently no plan for nightly Docker images at [graalvm/container](https://github.com/graalvm/container).

I want to thank you for your work and efforts (including this nice PR) to ship TruffleRuby as docker images.

**Comment by eregon** [comment]
We are now able to merge this PR, now that releases are made from truffleruby/truffleruby :tada: 
@flavorjones Thank you!
I'll merge this as-is and add some tweaks on top in another PR.

**Pull request closed without merging**
