### PR TITLE
Improve compatibility of RUBY_PLATFORM

### PR DESCRIPTION
**Pull request by chrisseaton**
https://github.com/Shopify/truffleruby/issues/1

@eightbitraptor

### CODE REVIEW

**Comment by chrisseaton** [comment]
Matt is a Shopify employee.

**Comment by eregon** [comment]
Thank you for the PR!

From https://github.com/eregon/actions-shell/runs/327245855, `RUBY_PLATFORM` is
- on Linux: `x86_64-linux`
- on macOS: `x86_64-darwin18`
- on Windows: `x64-mingw32`

So the kernel version only seems used on macOS.

**Comment by chrisseaton** [comment]
Have you taken a look at `--with-os-version-style=`? We think `major` is the default (but I'm not used to reading these Autoconf files). We're trying to match a default build. We found gems in the wild depending on this https://github.com/freerange/mocha/blob/master/lib/mocha/macos_version.rb.

**Comment by eregon** [comment]
The value of `RUBY_PLATFORM` seems to come form autoconf's `$target_os`.
In any case, let's match MRI, so on macOS we need the version as this PR does, but on Linux (and I think for other platforms too) we shouldn't have it:
The added spec does not pass on MRI on Linux:
```
$ jt -u ruby test spec/ruby/core/builtin_constants/builtin_constants_spec.rb
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
                                                                                             
1)
RUBY_PLATFORM contains the current kernel major version FAILED
Expected "x86_64-linux" =~ /5/
to be truthy but was nil
/home/eregon/code/truffleruby-ws/truffleruby/spec/ruby/core/builtin_constants/builtin_constants_spec.rb:41:in `block (3 levels) in <top (required)>'
/home/eregon/code/truffleruby-ws/truffleruby/spec/ruby/core/builtin_constants/builtin_constants_spec.rb:33:in `<top (required)>'
```

**Comment by eightbitraptor** [comment]
Thanks for the feedback @eregon and @chrisseaton - I've pushed a commit that restricts this functionailty to Darwin based OS's only now, and uses the original behaviour for other systems. I've run the tests locally on both Ubuntu 18.04 and macOS 10.15.2 so I'm hopeful 👍 

I think it's important to note that we're only replicating the _default_ behaviour of MRI at this stage. I don't have much context about what the `--with-os-version-style` flag is used for, only that it's possible to compile Ruby with a different setting.

Thanks both.

**Comment by eregon** [comment]
Thanks for the update, I'll integrate the PR.

> https://github.com/freerange/mocha/blob/master/lib/mocha/macos_version.rb

FWIW, a better way to do that seems to be `Etc.uname[:release]`.

I guess 99+% don't set `--with-os-version-style`, so let's not worry about until we find a problem related to it.

**Comment by eregon** [comment]
@chrisseaton Could you remove the last commit?
I did the formatting and a few small fixes on top, so rebasing is not easy and the PR already passed CI.

The issue is that if there is an extra commit on the GitHub PR it won't be regarded as "merged" on GitHub (but just closed).

To avoid this kind of issue I add the label `in-ci` when creating the internal PR.
The label `in-ci` means the PR is being tested in the internal CI and no new commits should be pushed on the GitHub PR.

**Comment by chrisseaton** [comment]
Done.

**Comment by eregon** [comment]
@eightbitraptor @chrisseaton Merged in 83abd2e344d3840c6925e73be8f45ba94f150161 with a few tweaks, thank you for the PR!

**Pull request merged**
