### PR TITLE
Make Enumerable#each_cons and #each_slice return the receiver

### PR DESCRIPTION
**Pull request by jcmfernandes**
Replicate [GH-1509](https://github.com/ruby/ruby/pull/1509).

### CODE REVIEW

**Comment by eregon** [comment]
Thank you for the PR!

Could you make sure this changes is tested by specs?
To do so, look under `spec/ruby`:
* If there is already a spec, use `jt untag` (after `jt build`) to include the previously-failing specs
* If there is no spec testing this yet, please add one (using `ruby_version_is`)

**Comment by nirvdrum** [comment]
@jcmfernandes If you need help writing a spec, let me know. We're also active on the GraalVM Slack instance in the #truffleruby team.

**Comment by nirvdrum** [comment]
@jcmfernandes Ping. I'd like to help get this merged. Do you think you'll have any time to look at it soon?

**Comment by eregon** [comment]
@nirvdrum This was fixed in https://github.com/oracle/truffleruby/commit/2fba2991ef95dff29349b93116f50f0381524d01.

**Pull request closed without merging**
