### PR TITLE
Add an alias of Kernel#yield_self named #then.

### PR DESCRIPTION
**Pull request by zhublik**

### CODE REVIEW

**Comment by chrisseaton** [comment]
Thanks - are you happy to sign the OCA?

**Comment by zhublik** [comment]
Yes. I've sent the signed OCA.

**Comment by chrisseaton** [comment]
Ok great - sorry it'll take a few days to come through though. I'll have to let this PR sit here until it does. We appreciate the contribution.

**Comment by zhublik** [comment]
Thank you so much!

**Comment by zhublik** [comment]
The signed OCA has been processed.

**Comment by chrisseaton** [comment]
It's not on the list yet. Did you get an email telling you it was accepted?

**Comment by zhublik** [comment]
Yes, i got it and can see my name: Dzmitry Meshcharakou in the list. Maybe the issue is that sometime ago i’ve changed the name on github and graalvm bot looks for an old unformal one.. I’ve sent OCA using the email from graalvm bot comment.

**Pull request merged**
