### PR TITLE
Special form for calling instance methods on a class

### PR DESCRIPTION
**Pull request by chrisseaton**
Because `my_class[:class].getName` is ugly - `my_class.class.getName` is a little better.

### CODE REVIEW

**Comment by eregon** [comment]
I'm not sure it's good to have special handling like this.
`my_class[:class].getName` is not so nice, but how often do you need it?
Shouldn't `Java.type('...').inspect` or `to_s` already give a nice debuggable representation?

I'm concerned introducing special cases like this will cause more confusion.
If people see you can do javaClass.class like in JS and that's sending a READ, then they would expect obj.foo would also be a READ but it's not. It might take a while until they find out we special-case `class` on Java classes.
Also this could be confusing with JRuby allowing `obj.class` to be used to call `obj.getClass`.

Another way to address this could be to have Truffle support INVOKE(javaClass, "class") and return the Class instance (shouldn't conflict with any static method as `class` is a keyword).

The rest of the PR looks good.

**Comment by chrisseaton** [comment]
> `my_class[:class].getName` is not so nice, but how often do you need it?

I've just been writing specs myself, but I've added it because I thought it was cumbersome.

> Shouldn't `Java.type('...').inspect` or `to_s` already give a nice debuggable representation?

At the moment `inspect` gives you a string like `<Foreign@0xXXXX>`. `to_s` doesn't do anything. We don't have any way to call `toString` on a Java object actually as far as I can remember.

> If people see you can do javaClass.class like in JS and that's sending a READ, then they would expect obj.foo would also be a READ but it's not.

You'd only think that if you were already aware of how `class` was implemented internally with Truffle, which is only if you're a Truffle language implementor. So you and I, not users.

Most people I think will want to call instance members, so will read out documentation to see how to do that, which is nicer if it's `.class` rather than `[:class]`.

**Comment by eregon** [comment]
> At the moment inspect gives you a string like `<Foreign@0xXXXX>`. to_s doesn't do anything. We don't have any way to call toString on a Java object actually as far as I can remember.

I think we should improve that, at least for Java/host objects, like `<MyJavaClass@0xXXXX>`.
Calling `toString()` should be possible via `INVOKE`, no?

> You'd only think that if you were already aware of how class was implemented internally with Truffle, which is only if you're a Truffle language implementor. So you and I, not users.

Right, for users they might just assume `my_class` responds to a `class` method, and that's fine.
I'm still a bit concerned it will confuse us and other Truffle people though.
`.class` has a nice symmetry with the Java syntax `Foo.class`.

In conclusion, I think it's OK to have this special syntax, but I can only hope it won't conflict with anything else or cause too much confusion.

**Comment by chrisseaton** [comment]
Maybe we could call it `.instance_object` instead?

**Pull request merged**
