### PR TITLE
Outline icon in white for dark backgrounds

### PR DESCRIPTION
**Pull request by chrisseaton**

### CODE REVIEW

**Comment by chrisseaton** [comment]
Screenshot 2021-07-29 at 00 36 00

**Comment by eregon** [comment]
I don't think we want to change the original logo just for dark mode.
For instance if the background is clear but not white, the outline seems less nice and redundant.
How about adding a separate folder under `logo` with the outline variant instead, or using some suffix like `_outline` in filenames of the variant?

**Comment by chrisseaton** [comment]
Done as a special case.

**Review by eregon — APPROVED** [review]
Thanks!

**Pull request merged**
