### PR TITLE
[Ruby 3.0 support] Add sorting for Dir.glob

### PR DESCRIPTION
**Pull request by Strech**
I've started the check and it turns out that sorting is not yet implemented in `Dir.glob` in both default and extended behaviour (`sort: Boolean` version).

I start adding flags and also add new test case for non-false value of the sort option https://github.com/ruby/spec/pull/894

### CODE REVIEW

**Comment by eregon** [comment]
Ah, @aardvark179 removed it in 56ed1c2cf244e79548fb084b500a8f713607a7d5, I forgot.
Basically you need to add it back there, and pass the `sort:` value until there (can be via an extra argument or flags).

**Comment by Strech** [comment]
Thanks @eregon will check also some other specs regarding respecting `{}` order

**Comment by Strech** [comment]
@eregon I decide to go with flags for internal ruby code to keep just one interface there.

**Review by eregon — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
