### PR TITLE
Update version number in the changelog

### PR DESCRIPTION
**Pull request by chrisseaton**

### CODE REVIEW

**Comment by chrisseaton** [comment]
We'll mark the upcoming version as 1.0, and then when we decide to do another RC we'll go back and change the previous one to 1.0-RCn and add a new 1.0.

**Comment by claudiug** [comment]
@chrisseaton 1.0 means ready for use in more production mode?

**Comment by claudiug** [comment]
@chrisseaton for ruby, any changes for next year?

**Comment by chrisseaton** [comment]
Yes a few overall GraalVM announcements but they will coincide with the release publicity so they're not public yet. I'll probably follow up with a status email about TruffleRuby in general since we didn't do one at the new year.

**Pull request merged**
